"""
COMP-1202 — Decision explainability (Epic 6, Domain 12)

Where provenance (COMP-1201) records *what* produced a score, explainability
narrates *why*: per-dimension reasoning, an overall-score rationale, and a
bucket-assignment (Hot/Warm/Cold) justification — in human-readable terms an
auditor or account owner can read (GDPR Art. 22 "meaningful information about
the logic involved").

Design decision — explanations are DETERMINISTIC, not LLM-written:
the explainer is a pure function over the ScoringResult breakdown. Same score
in => same explanation out. This keeps explanations reproducible and auditable
(the system's core selling point) and avoids circular provenance (explaining an
LLM-influenced score with yet another LLM call). When the LLM fallback did run,
that fact is surfaced from provenance and stated plainly in the explanation,
rather than the explanation itself being generated by an LLM.

Sub-task coverage:
- ST1: ScoreExplanation model — the explainability framework / data structure.
- ST2: per-dimension reasoning (DimensionExplanation).
- ST3: overall-score reasoning (summary + top contributors / detractors).
- ST4: bucket-assignment reasoning (why Hot vs Warm vs Cold).

The generator reads the same breakdown dict that ScoringResult.model_dump()
produces, so it works off stored scores (for the retrieval API) without
re-running the engine.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


# --------------------------------------------------------------------------- #
# ST1 — explainability data model                                             #
# --------------------------------------------------------------------------- #
class DimensionExplanation(BaseModel):
    """ST2 — why one dimension scored what it did."""

    dimension: str
    points: float = Field(..., description="Points earned in this dimension")
    max_points: float = Field(..., description="Dimension budget (max possible)")
    fired_signals: list[str] = Field(
        default_factory=list, description="Signals that contributed points"
    )
    missed_signals: list[str] = Field(
        default_factory=list, description="Signals that did not fire / were skipped"
    )
    reasoning: str = Field(..., description="Human-readable explanation")


class ScoreExplanation(BaseModel):
    """The full explanation attached to / derived from a ScoringResult."""

    lead_id: str
    score: float
    classification: str

    # ST3 — overall reasoning
    summary: str = Field(..., description="One-paragraph overall rationale")
    top_contributors: list[str] = Field(
        default_factory=list, description="Dimensions/signals that lifted the score most"
    )
    top_detractors: list[str] = Field(
        default_factory=list, description="What held the score back"
    )

    # ST2 — per-dimension reasoning
    dimensions: list[DimensionExplanation] = Field(default_factory=list)

    # ST4 — bucket assignment reasoning
    bucket_reasoning: str = Field(
        ..., description="Why this score maps to this Hot/Warm/Cold bucket"
    )

    # surfaced from provenance — stated, not LLM-generated
    llm_assisted: bool = Field(
        default=False, description="Whether the LLM fallback influenced this score"
    )
    blocked: bool = Field(default=False, description="Whether a hard block applied")


# --------------------------------------------------------------------------- #
# Generator — pure function over a score breakdown                            #
# --------------------------------------------------------------------------- #
# Default Hot/Warm/Cold thresholds. >>> CONFIRM against your engine's actual
# classification cutoffs; these are read from the breakdown when present.
DEFAULT_HOT_MIN = 70.0
DEFAULT_WARM_MIN = 40.0


class ExplanationGenerator:
    """Builds a ScoreExplanation from a stored score breakdown dict."""

    def __init__(
        self, *, hot_min: float = DEFAULT_HOT_MIN, warm_min: float = DEFAULT_WARM_MIN
    ) -> None:
        self._hot_min = hot_min
        self._warm_min = warm_min

    def explain(self, breakdown: dict[str, Any]) -> ScoreExplanation:
        lead_id = str(breakdown.get("lead_id", "unknown"))
        score = float(breakdown.get("score", 0.0))
        classification = str(breakdown.get("classification", "cold"))

        provenance = breakdown.get("provenance") or {}
        llm_assisted = provenance.get("scorer") == "llm_fallback"
        blocked = classification.lower() == "blocked"

        dims = self._explain_dimensions(breakdown)
        contributors, detractors = self._rank(dims)

        return ScoreExplanation(
            lead_id=lead_id,
            score=score,
            classification=classification,
            summary=self._summary(score, classification, dims, blocked, llm_assisted),
            top_contributors=contributors,
            top_detractors=detractors,
            dimensions=dims,
            bucket_reasoning=self._bucket_reasoning(score, classification, blocked),
            llm_assisted=llm_assisted,
            blocked=blocked,
        )

    # -- ST2: per-dimension reasoning --------------------------------------- #
    def _explain_dimensions(self, breakdown: dict[str, Any]) -> list[DimensionExplanation]:
        dim_scores = breakdown.get("dimension_scores") or {}
        out: list[DimensionExplanation] = []
        for name, data in dim_scores.items():
            if not isinstance(data, dict):
                continue
            points = float(data.get("capped_points", data.get("points", 0.0)))
            max_points = float(data.get("max_points", data.get("budget", 0.0)) or 0.0)
            fired = list(data.get("fired_signals", []) or [])
            missed = list(data.get("missed_signals", data.get("skipped_signals", [])) or [])
            out.append(
                DimensionExplanation(
                    dimension=name,
                    points=points,
                    max_points=max_points,
                    fired_signals=fired,
                    missed_signals=missed,
                    reasoning=self._dimension_reasoning(name, points, max_points, fired, missed),
                )
            )
        return out

    @staticmethod
    def _dimension_reasoning(
        name: str, points: float, max_points: float, fired: list[str], missed: list[str]
    ) -> str:
        if max_points and points >= max_points:
            head = f"{name} scored the full {points:.0f} points"
        elif points == 0:
            head = f"{name} scored no points"
        else:
            cap = f" of {max_points:.0f}" if max_points else ""
            head = f"{name} earned {points:.0f}{cap} points"
        if fired:
            head += f", driven by {_join(fired)}"
        if missed:
            head += f". {_capitalise(_join(missed))} did not fire"
        return head + "."

    # -- ST3: overall reasoning --------------------------------------------- #
    @staticmethod
    def _rank(dims: list[DimensionExplanation]) -> tuple[list[str], list[str]]:
        # contributors: dimensions with the most points; detractors: biggest gaps
        by_points = sorted(dims, key=lambda d: d.points, reverse=True)
        contributors = [d.dimension for d in by_points if d.points > 0][:3]
        by_gap = sorted(dims, key=lambda d: (d.max_points - d.points), reverse=True)
        detractors = [
            d.dimension for d in by_gap if (d.max_points - d.points) > 0
        ][:3]
        return contributors, detractors

    def _summary(
        self,
        score: float,
        classification: str,
        dims: list[DimensionExplanation],
        blocked: bool,
        llm_assisted: bool,
    ) -> str:
        if blocked:
            return (
                f"This lead was hard-blocked and assigned a score of {score:.0f}. "
                "A disqualifying condition (backed by sufficiently confident data) "
                "stopped scoring before dimensions were evaluated."
            )
        earned = sum(d.points for d in dims)
        possible = sum(d.max_points for d in dims) or 0.0
        frac = f"{earned:.0f} of {possible:.0f} available points" if possible else f"{score:.0f} points"
        strongest = max(dims, key=lambda d: d.points).dimension if dims else None
        msg = (
            f"This lead scored {score:.0f}, earning {frac}, and was classified "
            f"{classification.upper()}."
        )
        if strongest:
            msg += f" Its strongest dimension was {strongest}."
        if llm_assisted:
            msg += (
                " Some signals were missing, so the LLM fallback estimated them "
                "before the deterministic engine produced the final score."
            )
        return msg

    # -- ST4: bucket assignment reasoning ----------------------------------- #
    def _bucket_reasoning(self, score: float, classification: str, blocked: bool) -> str:
        if blocked:
            return (
                "Classified BLOCKED because a hard disqualifier applied; the "
                "numeric thresholds were not used."
            )
        cls = classification.lower()
        if cls == "hot":
            return (
                f"Classified HOT because the score of {score:.0f} meets or exceeds "
                f"the Hot threshold of {self._hot_min:.0f}."
            )
        if cls == "warm":
            return (
                f"Classified WARM because the score of {score:.0f} falls between the "
                f"Warm threshold of {self._warm_min:.0f} and the Hot threshold of "
                f"{self._hot_min:.0f}."
            )
        return (
            f"Classified COLD because the score of {score:.0f} is below the Warm "
            f"threshold of {self._warm_min:.0f}."
        )


# --------------------------------------------------------------------------- #
# small text helpers                                                          #
# --------------------------------------------------------------------------- #
def _join(items: list[str]) -> str:
    items = [str(i) for i in items]
    if not items:
        return ""
    if len(items) == 1:
        return items[0]
    if len(items) == 2:
        return f"{items[0]} and {items[1]}"
    return f"{', '.join(items[:-1])}, and {items[-1]}"


def _capitalise(text: str) -> str:
    return text[:1].upper() + text[1:] if text else text
