"""add platform_event_id to lead_touchpoints

Revision ID: 0149ad5bb26e
Revises: c8d2f1a9e3b7
Create Date: 2026-06-16 17:08:20.952360

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0149ad5bb26e'
down_revision: str | None = 'c8d2f1a9e3b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_connections_metadata_gin'), table_name='channel_connections', postgresql_using='gin')
    op.add_column('lead_touchpoints', sa.Column('platform_event_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_lead_touchpoints_platform_event_id'), 'lead_touchpoints', ['platform_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_touchpoints_platform_event_id'), table_name='lead_touchpoints')
    op.drop_column('lead_touchpoints', 'platform_event_id')
    op.create_index(op.f('ix_channel_connections_metadata_gin'), 'channel_connections', ['metadata'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
