"""lead_ingestion_and_channel_connection_models

Revision ID: 4f55595dc4ff
Revises: 8fccb46cd58e
Create Date: 2026-06-11 20:40:52.018379

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f55595dc4ff'
down_revision: str | None = '8fccb46cd58e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('credentials_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_connections_tenant_id'), 'channel_connections', ['tenant_id'], unique=False)
    op.create_table('lead_form_field_maps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source_field_name', sa.String(), nullable=False),
    sa.Column('canonical_field_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_field_name', name='uq_field_map_tenant_source_field')
    )
    op.create_index(op.f('ix_lead_form_field_maps_tenant_id'), 'lead_form_field_maps', ['tenant_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('channel_connection_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_stage', sa.String(), nullable=False),
    sa.Column('source_channel', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('raw_event_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pre_flight_block_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_connection_id'], ['channel_connections.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_channel_connection_id'), 'leads', ['channel_connection_id'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_table('intake_event_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('platform_event_id', sa.String(), nullable=False),
    sa.Column('source_channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_event_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_event_id', name='uq_intake_event_log_platform_event_id')
    )
    op.create_index(op.f('ix_intake_event_logs_lead_id'), 'intake_event_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_intake_event_logs_tenant_id'), 'intake_event_logs', ['tenant_id'], unique=False)
    op.create_table('lead_touchpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('source_channel', sa.String(), nullable=False),
    sa.Column('raw_event_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_touchpoints_lead_id'), 'lead_touchpoints', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_touchpoints_lead_id'), table_name='lead_touchpoints')
    op.drop_table('lead_touchpoints')
    op.drop_index(op.f('ix_intake_event_logs_tenant_id'), table_name='intake_event_logs')
    op.drop_index(op.f('ix_intake_event_logs_lead_id'), table_name='intake_event_logs')
    op.drop_table('intake_event_logs')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_channel_connection_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_lead_form_field_maps_tenant_id'), table_name='lead_form_field_maps')
    op.drop_table('lead_form_field_maps')
    op.drop_index(op.f('ix_channel_connections_tenant_id'), table_name='channel_connections')
    op.drop_table('channel_connections')
    # ### end Alembic commands ###
