"""add_partial_unique_indexes_leads_phone_email

Revision ID: 70e8a8c1f36f
Revises: e5b9e051e0bf
Create Date: 2026-06-25 01:15:11.494862

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e8a8c1f36f'
down_revision: str | None = 'e5b9e051e0bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_lead_tenant_email', 'leads', ['tenant_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uq_lead_tenant_phone', 'leads', ['tenant_id', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_lead_tenant_phone', table_name='leads', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_index('uq_lead_tenant_email', table_name='leads', postgresql_where=sa.text('email IS NOT NULL'))
    # ### end Alembic commands ###
