"""create tenants table

Revision ID: 7c984ef0d9e8
Revises:
Create Date: 2026-05-31 23:57:37.377992

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c984ef0d9e8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('primary_contact_name', sa.String(), nullable=False),
    sa.Column('primary_contact_email', sa.String(), nullable=False),
    sa.Column('business_type', sa.Enum('B2B', 'B2C', name='business_type'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVE', 'SUSPENDED', 'CHURNED', name='tenant_status'), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('language_preference', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    # ### end Alembic commands ###
