"""add_retention_event_logs

Revision ID: b962eecc4417
Revises: 2b4e569e8653
Create Date: 2026-06-24 15:17:50.158124

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b962eecc4417'
down_revision: str | None = '2b4e569e8653'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_event_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retention_days_applied', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_event_logs_lead_id'), 'retention_event_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_retention_event_logs_tenant_id'), 'retention_event_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_event_logs_tenant_id'), table_name='retention_event_logs')
    op.drop_index(op.f('ix_retention_event_logs_lead_id'), table_name='retention_event_logs')
    op.drop_table('retention_event_logs')
    # ### end Alembic commands ###
