"""add_erasure_event_logs

Revision ID: e5b9e051e0bf
Revises: b962eecc4417
Create Date: 2026-06-24 15:36:35.275811

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5b9e051e0bf'
down_revision: str | None = 'b962eecc4417'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erasure_event_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('erased_lead_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('identifier_type', sa.String(), nullable=False),
    sa.Column('identifier_hash', sa.String(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erasure_event_logs_tenant_id'), 'erasure_event_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erasure_event_logs_tenant_id'), table_name='erasure_event_logs')
    op.drop_table('erasure_event_logs')
    # ### end Alembic commands ###
